### ISSUE TITLE
not able to read long string within a tag

### ISSUE THREAD

**Issue by justgig8** [nfarina/webrequest#3]
Reading a tag value but am not getting the whole string but just a part of it.
For example in the below example, 
- what I should get  = "Kathua with Baileys and Triple Sec" 
- what am getting    = "Kathua with Baileys and T…"

Am using below code:

SMXMLElement *summaryElement = [item childNamed:@"summary"];
NSString *isummary = [summaryElement value];  
NSLog(@"summary: %@", isummary);

to read following xml:

<item identifier="it224" name="B-52">
      <summary>Kathua with Baileys and Triple Sec</summary>
</item>

Is there any length limit while reading a tag value???

**Comment by justgig8** [comment]
Can you please solve this soon as am stuck in project since I have realized am not able to extract full string values from tags??

I really love your code snippets but am stuck for now :(

**Comment by nfarina** [comment]
Are you sure you're running the code you printed above?

When I execute this code:

```
SMXMLDocument *document = [SMXMLDocument documentWithData:data error:&error];
SMXMLElement *item = document.root;
SMXMLElement *summaryElement = [item childNamed:@"summary"];
NSString *isummary = [summaryElement value];

NSLog(@"summary: %@", isummary);
```

...against your sample XML document, it prints the whole value "Kathua with Baileys and Triple Sec".

Are you trying to "re-parse" an XML document that was already parsed with `SMXMLDocument`? Because if you try to get the XML string back by calling `-description()`, then the values will be truncated like you illustrated.

**Comment by justgig8** [comment]
Yes.

I was re-parsing it.
Should that cause any such behaviour??

On Mon, Mar 5, 2012 at 12:48 AM, Nick Farina
reply@reply.github.com
wrote:

**Comment by justgig8** [comment]
Should getting the XML string back of a child from the main XML - make it behave this way??
You can't avoid that???

**Comment by nfarina** [comment]
So `SMXMLDocument` is not designed to be a "roundtrip" solution for converting XML to objects and back to text, or for generating new XML structures. It only wraps the native `NSXMLParser` to make reading XML easier.

However `SMXMLElement` does now expose a `-fullDescription` method which will print out the XML structure as text without truncating the values. You might try that, although it won't preserve all the XML data like whitespace and CDATA nodes and proper character escaping.

**Comment by justgig8** [comment]
But that limits its functionality.

Suppose I just want to read a tag value from the XML and then take a decision based on that, decision of sending the rest of the xml to other subsequent parsers.
How will I be able to achieve this??

**Comment by nfarina** [comment]
Yes, this is a limit to its functionality, I didn't do the extra work of guaranteeing complete and true XML text generation because I considered it to be outside the scope of "reading XML" which is what `SMXMLDocument` is intended for.

You could certainly write this function yourself as a category method on `SMXMLElement` if you require correct XML text generation. You could start by inspecting the `-description` code to see what's involved.

Or you could have your subsequent parsers accept `SMXMLElement` instances instead of XML text snippets. But I realize that the "subsequent parsers" code may be out of your control.

**Comment by justgig8** [comment]
finally passed the SMXMLElement only to the rest of the parsers. It worked as expected. Thanks a lot. I mean it.

**Comment by nfarina** [comment]
No problem, glad you found a solution!
